const data = [ 
  {id:0, reading:'ああ', kanjis:'', type:'int', meaning:'Ah!, Oh!'},
  {id:1, reading:'あう', kanjis:'会う', type:'u-v', meaning:'to meet, to see'}, 
  {id:2, reading:'あお', kanjis:'青', type:'n', meaning:'blue'},
  {id:3, reading:'あおい', kanjis:'青い', type:'adj', meaning:'blue'},
  {id:4, reading:'あか', kanjis:'赤', type:'n', meaning:'red'},
  {id:5, reading:'あかい', kanjis:'赤い', type:'adj', meaning:'red'},
  {id:6, reading:'あかるい', kanjis:'明るい', type:'adj', meaning:'bright, cheerful'},
  {id:7, reading:'あき', kanjis:'秋', type:'n-adv', meaning:'autumn, fall'}, 
  {id:8, reading:'あく', kanjis:'開く', type:'u-v,vi', meaning:'to open, to become open'},
  {id:9, reading:'あける', kanjis:'開ける', type:'ru-v', meaning:'to open'},
  {id:10, reading:'あげる', kanjis:'上げる', type:'ru-v', meaning:'to give'},
  {id:11, reading:'あさ', kanjis:'朝', type:'n-adv,n-t', meaning:'morning'},
  {id:12, reading:'あさごはん', kanjis:'朝御飯', type:'n', meaning:'breakfast'},
  {id:13, reading:'あさって', kanjis:'', type:'n-adv,n-t', meaning:'day after tomorrow'},
  {id:14, reading:'あし', kanjis:'足', type:'n', meaning:'foot, leg'},
  {id:15, reading:'あした', kanjis:'', type:'n-t', meaning:'tomorrow'},
  {id:16, reading:'あそこ', kanjis:'', type:'n', meaning:'there, over there, that place'},
  {id:17, reading:'あそぶ', kanjis:'遊ぶ', type:'u-v', meaning:'to play, to enjoy oneself'},
  {id:18, reading:'あたたかい', kanjis:'暖かい', type:'adj', meaning:'warm, mild'},
  {id:19, reading:'あたま', kanjis:'頭', type:'n', meaning:'head'},
  {id:20, reading:'あたらしい', kanjis:'新しい', type:'adj', meaning:'new'},
  {id:21, reading:'あちら', kanjis:'', type:'n', meaning:'there, yonder, that'},
  {id:22, reading:'あつい', kanjis:'暑い', type:'adj', meaning:'hot, warm'},
  {id:23, reading:'あつい', kanjis:'熱い', type:'adj', meaning:'hot (thing)'},
  {id:24, reading:'あつい', kanjis:'厚い', type:'adj', meaning:'kind, warm(hearted), thick, deep'},
  {id:25, reading:'あっち', kanjis:'', type:'n col', meaning:'over there'},
  {id:26, reading:'あと', kanjis:'後', type:'adj-no,n', meaning:'afterwards, since then, in the future'},
  {id:27, reading:'あなた', kanjis:'', type:'n', meaning:'you'},
  {id:28, reading:'あに', kanjis:'兄', type:'n', meaning:'(hum) older brother'},
  {id:29, reading:'あね', kanjis:'姉', type:'n', meaning:'(hum) older sister'},
  {id:30, reading:'あの', kanjis:'', type:'pren-adj', meaning:'that over there'},
  {id:31, reading:'あの', kanjis:'', type:'int', meaning:'um...'},
  {id:32, reading:'アパート', kanjis:'', type:'n,adv', meaning:'apartment (abbr)'},
  {id:33, reading:'あびる', kanjis:'', type:'ru-v', meaning:'to bathe, to shower'},
  {id:34, reading:'あぶない', kanjis:'危ない', type:'adj', meaning:'dangerous, critical, watch out!'},
  {id:35, reading:'あまい', kanjis:'甘い', type:'adj,expr', meaning:'generous, sweet'},
  {id:36, reading:'あまり', kanjis:'', type:'na-adj,adv,n,n-suf', meaning:'not very, not much'},
  {id:37, reading:'あめ', kanjis:'雨', type:'n', meaning:'rain'},
  {id:38, reading:'あめ', kanjis:'飴', type:'n', meaning:'(hard) candy, toffee'},
  {id:39, reading:'あらう', kanjis:'洗う', type:'u-v', meaning:'to wash'},
  {id:40, reading:'ある [存在]', kanjis:'', type:'u-v-i', meaning:'to be'},
  {id:41, reading:'ある [所有]', kanjis:'', type:'u-v-i', meaning:'to have'},
  {id:42, reading:'あるく', kanjis:'歩く', type:'u-v', meaning:'to walk'},
  {id:43, reading:'あれ', kanjis:'', type:'int,n', meaning:'that, that thing'},
  {id:44, reading:'いい/よい', kanjis:'', type:'adj', meaning:'good'},
  {id:45, reading:'いいえ', kanjis:'', type:'int,n', meaning:'no, not at all'},
  {id:46, reading:'いう', kanjis:'言う', type:'u-v', meaning:'to say'},
  {id:47, reading:'いえ', kanjis:'家', type:'suf', meaning:'house, family'},
  {id:48, reading:'いかが', kanjis:'', type:'na-adj,adv,n', meaning:'how, in what way'},
  {id:49, reading:'いく/ゆく', kanjis:'行く', type:'u-v', meaning:'to go'},
  {id:50, reading:'いくつ', kanjis:'', type:'n', meaning:'how many?, how old?'},
  {id:51, reading:'いくら', kanjis:'', type:'adv,n', meaning:'how much?, how many?'}, 
  {id:52, reading:'いけ', kanjis:'池', type:'n', meaning:'pond'},
  {id:53, reading:'いしゃ', kanjis:'医者', type:'n', meaning:'doctor (medical)'},
  {id:54, reading:'いす', kanjis:'', type:'n', meaning:'chair'},
  {id:55, reading:'いそがしい', kanjis:'忙しい', type:'adj', meaning:'busy, irritated'},
  {id:56, reading:'いたい', kanjis:'痛い', type:'adj', meaning:'painful'},
  {id:57, reading:'いち', kanjis:'一', type:'num', meaning:'one'},
  {id:58, reading:'いちにち', kanjis:'一日', type:'n', meaning:'1 day (duration)'},
  {id:59, reading:'いちばん', kanjis:'', type:'n-adv', meaning:'best, first, number one'},
  {id:60, reading:'いつ', kanjis:'', type:'gn-adv', meaning:'when'}, 
  {id:61, reading:'いつか', kanjis:'五日', type:'n', meaning:'five days, the fifth day (of the month)'},
  {id:62, reading:'いっしょ', kanjis:'一緒', type:'adv,n', meaning:'together'},
  {id:63, reading:'いつつ', kanjis:'五つ', type:'n', meaning:'five'},
  {id:64, reading:'いつも', kanjis:'', type:'adv,n', meaning:'always, every time'},
  {id:65, reading:'いぬ', kanjis:'犬', type:'', meaning:'dog'},
  {id:66, reading:'いま', kanjis:'今', type:'', meaning:'now'},
  {id:67, reading:'いみ', kanjis:'意味', type:'n,vs', meaning:'meaning'},
  {id:68, reading:'いもうと', kanjis:'妹', type:'n', meaning:'younger sister'},
  {id:69, reading:'いや', kanjis:'嫌', type:'na-adj,n', meaning:'disagreeable, no'},
  {id:70, reading:'いりぐち', kanjis:'入口', type:'n', meaning:'entrance, gate'},
  {id:71, reading:'いる', kanjis:'居る', type:'u-v', meaning:'(hum) to be (animate), to exist'},
  {id:72, reading:'いる', kanjis:'要る', type:'u-v', meaning:'to need'},
  {id:73, reading:'いれる', kanjis:'入れる', type:'ru-v', meaning:'to put in'},
  {id:74, reading:'いろ', kanjis:'色', type:'n', meaning:'colour'},
  {id:75, reading:'いろいろ', kanjis:'', type:'na-adj,adj-no,adv,n', meaning:'various'},
  {id:76, reading:'うえ', kanjis:'上', type:'no-adj,n-adv,n,n-suf', meaning:'above, on top of'},
  {id:77, reading:'うしろ', kanjis:'後ろ', type:'n', meaning:'behind, rear'},
  {id:78, reading:'うすい', kanjis:'薄い', type:'adj', meaning:'thin, weak'},
  {id:79, reading:'うた', kanjis:'歌', type:'n', meaning:'song'},
  {id:80, reading:'うたう', kanjis:'歌う', type:'u-v', meaning:'to sing'},
  {id:81, reading:'うち', kanjis:'', type:'n', meaning:'house (one\'s own)'},
  {id:82, reading:'うまれる', kanjis:'生まれる', type:'ru-v', meaning:'to be born'}, 
  {id:83, reading:'うみ', kanjis:'海', type:'n', meaning:'sea, beach'},
  {id:84, reading:'うる', kanjis:'売る', type:'u-v', meaning:'to sell'},
  {id:85, reading:'うるさい', kanjis:'', type:'adj', meaning:'noisy, loud, annoying'},
  {id:86, reading:'うわぎ', kanjis:'上着', type:'n', meaning:'coat, jacket'},
  {id:87, reading:'え', kanjis:'絵', type:'n,n-suf', meaning:'picture, drawing, painting, sketch'},
  {id:88, reading:'えいが', kanjis:'映画', type:'n', meaning:'movie, film'},
  {id:89, reading:'えいがかん', kanjis:'映画館', type:'n', meaning:'movie theatre (theater), cinema'},
  {id:90, reading:'えいご', kanjis:'英語', type:'n', meaning:'the English language'},
  {id:91, reading:'ええ', kanjis:'', type:'conj,int,n', meaning:'yes'},
  {id:92, reading:'えき', kanjis:'駅', type:'n', meaning:'station'},
  {id:93, reading:'エレベーター', kanjis:'', type:'n', meaning:'elevator'},
  {id:94, reading:'～えん', kanjis:'～円', type:'n', meaning:'yen (currency)'},
  {id:95, reading:'えんぴつ', kanjis:'鉛筆', type:'n', meaning:'pencil'},
  {id:96, reading:'お～', kanjis:'', type:'prefix', meaning:'honourable ～ (honorific)'},
  {id:97, reading:'おいしい', kanjis:'', type:'adj', meaning:'delicious, tasty'},
  {id:98, reading:'おおい', kanjis:'多い', type:'adj', meaning:'many'},
  {id:99, reading:'おおきい', kanjis:'大きい', type:'adj', meaning:'big'},
  {id:100, reading:'おおきな', kanjis:'大きな', type:'na-adj', meaning:'big'},
  {id:101, reading:'おおぜい', kanjis:'大勢', type:'n', meaning:'great number of people'},
  {id:102, reading:'おかあさん', kanjis:'お母さん', type:'n', meaning:'(hon) mother'},
  {id:103, reading:'おかし', kanjis:'お菓子', type:'n', meaning:'confections, sweets, candy'},
  {id:104, reading:'おかね', kanjis:'お金', type:'n', meaning:'money'},
  {id:105, reading:'おきる', kanjis:'起きる', type:'ru-v', meaning:'to get up, to rise'},
  {id:106, reading:'おく', kanjis:'置く', type:'u-v', meaning:'to put, to place'},
  {id:107, reading:'おくさん', kanjis:'奥さん', type:'n', meaning:'(hon) wife'},
  {id:108, reading:'おさけ', kanjis:'お酒', type:'n', meaning:'alcohol, sake (rice wine)'},
  {id:109, reading:'おさら', kanjis:'お皿', type:'n', meaning:'plate, dish'}, 
  {id:110, reading:'おじ・さん', kanjis:'伯父/叔父・さん', type:'n', meaning:'uncle, middle aged man'},
  {id:111, reading:'おじいさん', kanjis:'', type:'n', meaning:'grandfather, male senior citizen'},
  {id:112, reading:'おしえる', kanjis:'教える', type:'ru-v', meaning:'to teach, to inform'},
  {id:113, reading:'おす', kanjis:'押す', type:'u-v,vt', meaning:'to push, to press'},
  {id:114, reading:'おそい', kanjis:'遅い', type:'adj', meaning:'late, slow'},
  {id:115, reading:'おちゃ', kanjis:'お茶', type:'n', meaning:'tea (green)'},
  {id:116, reading:'おてあらい', kanjis:'お手洗い', type:'', meaning:'toilet, lavatory, bathroom'},
  {id:117, reading:'おとうさん', kanjis:'お父さん', type:'n', meaning:'(hon) father'},
  {id:118, reading:'おとうと', kanjis:'弟', type:'n', meaning:'younger brother'},
  {id:119, reading:'おとこ', kanjis:'男', type:'n', meaning:'man'},
  {id:120, reading:'おとこのこ', kanjis:'男の子', type:'n', meaning:'boy'},
  {id:121, reading:'おととい', kanjis:'', type:'n-adv,n-t', meaning:'day before yesterday'},
  {id:122, reading:'おととし', kanjis:'', type:'n-adv,n-t', meaning:'year before last'},
  {id:123, reading:'おとな', kanjis:'大人', type:'n', meaning:'adult'},
  {id:124, reading:'おなか', kanjis:'', type:'n', meaning:'stomach'},
  {id:125, reading:'おなじ', kanjis:'同じ', type:'na-adj,n', meaning:'same, identical, similar'},
  {id:126, reading:'おにいさん', kanjis:'お兄さん', type:'n', meaning:'(hon) older brother'},
  {id:127, reading:'おねえさん', kanjis:'お姉さん', type:'n', meaning:'(hon) older sister'},
  {id:128, reading:'おばさん', kanjis:'伯母さん/叔母さん', type:'n', meaning:'aunt'},
  {id:129, reading:'おばあさん', kanjis:'', type:'n', meaning:'grandmother, female senior-citizen'},
  {id:130, reading:'おふろ', kanjis:'お風呂', type:'n', meaning:'bath'},
  {id:131, reading:'おべんとう', kanjis:'お弁当', type:'n', meaning:'boxed lunch'},
  {id:132, reading:'おぼえる', kanjis:'覚える', type:'ru-v', meaning:'to remember, to memorize'},
  {id:133, reading:'おまわりさん', kanjis:'', type:'n', meaning:'policeman (friendly term)'},
  {id:134, reading:'おもい', kanjis:'重い', type:'adj', meaning:'heavy'},
  {id:135, reading:'おもしろい', kanjis:'', type:'adj', meaning:'interesting, amusing'},
  {id:136, reading:'およぐ', kanjis:'泳ぐ', type:'u-v', meaning:'to swim'},
  {id:137, reading:'おりる', kanjis:'降りる', type:'ru-v', meaning:'to alight (eg from bus), to get off'},
  {id:138, reading:'おわる', kanjis:'終る', type:'u-v', meaning:'to finish, to close'},
  {id:139, reading:'おんがく', kanjis:'音楽', type:'n', meaning:'music'},
  {id:140, reading:'おんな', kanjis:'女', type:'n', meaning:'woman, girl, daughter'},
  {id:141, reading:'おんなのこ', kanjis:'女の子', type:'n', meaning:'girl'},
  {id:142, reading:'～かい', kanjis:'～回', type:'n', meaning:'counter for occurrences'},
  {id:143, reading:'～かい', kanjis:'～階', type:'n', meaning:'counter for storeys of a building'},
  {id:144, reading:'がいこく', kanjis:'外国', type:'n', meaning:'foreign country'},
  {id:145, reading:'がいこくじん', kanjis:'外国人', type:'n', meaning:'foreigner'},
  {id:146, reading:'かいしゃ', kanjis:'会社', type:'n', meaning:'company, corporation'},
  {id:147, reading:'かいだん', kanjis:'階段', type:'n', meaning:'stairs'},
  {id:148, reading:'かいもの', kanjis:'買い物', type:'n', meaning:'shopping'},
  {id:149, reading:'かう', kanjis:'買う', type:'u-v', meaning:'to buy'},
  {id:150, reading:'かえす', kanjis:'返す', type:'u-v,vt', meaning:'to return something'},
  {id:151, reading:'かえる', kanjis:'帰る', type:'u-v', meaning:'to go home, to return'},
  {id:152, reading:'かお', kanjis:'顔', type:'n', meaning:'face (person)'},
  {id:153, reading:'かかる', kanjis:'', type:'u-v,vi', meaning:'to take (eg time, money)'},
  {id:154, reading:'かぎ', kanjis:'', type:'n', meaning:'key/s'},
  {id:155, reading:'かく', kanjis:'書く', type:'u-v', meaning:'to write'},
  {id:156, reading:'がくせい', kanjis:'学生', type:'n', meaning:'student'},
  {id:157, reading:'～かげつ', kanjis:'～か月', type:'suf', meaning:'(number of) months'},
  {id:158, reading:'かける', kanjis:'', type:'ru-v', meaning:'to put on (eg glasses)'},
  {id:159, reading:'かける', kanjis:'', type:'ru-v', meaning:'to dial/call (eg phone)'}, 
  {id:160, reading:'かさ', kanjis:'傘', type:'n', meaning:'umbrella'},
  {id:161, reading:'かす', kanjis:'貸す', type:'u-v', meaning:'to lend'},
  {id:162, reading:'かぜ', kanjis:'風', type:'n', meaning:'wind, breeze'},
  {id:163, reading:'かぜ', kanjis:'風邪', type:'n', meaning:'cold, illness'},
  {id:164, reading:'かた', kanjis:'方', type:'n', meaning:'person'},
  {id:165, reading:'かぞく', kanjis:'家族', type:'n', meaning:'family'},
  {id:166, reading:'かたかな', kanjis:'片仮名', type:'n', meaning:'katakana'},
  {id:167, reading:'～がつ', kanjis:'～月', type:'suf', meaning:'month of year'},
  {id:168, reading:'がっこう', kanjis:'学校', type:'n', meaning:'school'},
  {id:169, reading:'カップ', kanjis:'', type:'n', meaning:'cup'},
  {id:170, reading:'かてい', kanjis:'家庭', type:'n', meaning:'home, household'},
  {id:171, reading:'かど', kanjis:'角', type:'n', meaning:'corner (e.g. desk)'},
  {id:172, reading:'かばん', kanjis:'', type:'n', meaning:'bag, basket'},
  {id:173, reading:'かびん', kanjis:'花瓶', type:'n', meaning:'(flower) vase'},
  {id:174, reading:'かぶる', kanjis:'', type:'u-v', meaning:'to wear, to put on (head)'},
  {id:175, reading:'かみ', kanjis:'紙', type:'n', meaning:'paper'},
  {id:176, reading:'カメラ', kanjis:'', type:'n', meaning:'camera'},
  {id:177, reading:'かようび', kanjis:'火曜日', type:'n-adv,n', meaning:'Tuesday'},
  {id:178, reading:'からい', kanjis:'辛い', type:'adj', meaning:'spicy, salty'},
  {id:179, reading:'からだ', kanjis:'体', type:'n', meaning:'body'},
  {id:180, reading:'かりる', kanjis:'借りる', type:'ru-v', meaning:'to borrow, to have a loan'},
  {id:181, reading:'～がる', kanjis:'', type:'suf', meaning:'feel'},
  {id:182, reading:'かるい', kanjis:'軽い', type:'adj', meaning:'light, non-serious, minor'},
  {id:183, reading:'カレー', kanjis:'', type:'n', meaning:'curry'},
  {id:184, reading:'カレンダー', kanjis:'', type:'n', meaning:'calendar'},
  {id:185, reading:'かわ', kanjis:'川/河', type:'n', meaning:'river'},
  {id:186, reading:'～がわ', kanjis:'側', type:'n-suf', meaning:'～ side'},
  {id:187, reading:'かわいい', kanjis:'', type:'adj', meaning:'cute, charming'},
  {id:188, reading:'かんじ', kanjis:'漢字', type:'n', meaning:'kanji, Chinese character'},
  {id:189, reading:'き', kanjis:'木', type:'n', meaning:'tree, wood'},
  {id:190, reading:'きいろ', kanjis:'黄色', type:'n', meaning:'yellow'},
  {id:191, reading:'きいろい', kanjis:'黄色い', type:'adj', meaning:'yellow'},
  {id:192, reading:'きえる', kanjis:'消える', type:'ru-v', meaning:'to go out, to vanish'},
  {id:193, reading:'きく', kanjis:'聞く', type:'u-v', meaning:'to hear, to listen, to ask'},
  {id:194, reading:'きた', kanjis:'北', type:'', meaning:'north'},
  {id:195, reading:'ギター', kanjis:'', type:'n', meaning:'guitar'},
  {id:196, reading:'きたない', kanjis:'汚い', type:'adj', meaning:'dirty, messy'},
  {id:197, reading:'きっさてん', kanjis:'喫茶店', type:'n', meaning:'coffee lounge'},
  {id:198, reading:'きって', kanjis:'切手', type:'n', meaning:'stamp (eg. postage)'},
  {id:199, reading:'きっぷ', kanjis:'切符', type:'n', meaning:'ticket'},
  {id:200, reading:'きのう', kanjis:'昨日', type:'n-adv,n-t', meaning:'yesterday'},
  {id:201, reading:'きゅう', kanjis:'九', type:'num', meaning:'nine'},
  {id:202, reading:'ぎゅうにく', kanjis:'牛肉', type:'n', meaning:'beef'},
  {id:203, reading:'ぎゅうにゅう', kanjis:'牛乳', type:'n', meaning:'milk'},
  {id:204, reading:'きょう', kanjis:'今日', type:'n-t', meaning:'today, this day'},
  {id:205, reading:'きょうしつ', kanjis:'教室', type:'n', meaning:'classroom'},
  {id:206, reading:'きょうだい', kanjis:'兄弟', type:'n', meaning:'siblings (brothers and sisters)'},
  {id:207, reading:'きょねん', kanjis:'去年', type:'n-adv,n-t', meaning:'last year'},
  {id:208, reading:'きらい', kanjis:'嫌い', type:'na-adj,n', meaning:'dislike, hate'},
  {id:209, reading:'きる', kanjis:'切る', type:'suf,u-v', meaning:'to cut, to chop'},
  {id:210, reading:'きる', kanjis:'着る', type:'ru-v', meaning:'to wear, to put on (from shoulders down)'},
  {id:211, reading:'きれい', kanjis:'', type:'na-adj', meaning:'pretty, clean, nice, tidy'},
  {id:212, reading:'キロ/キログラム', kanjis:'', type:'n,pref', meaning:'kilo (kilogram)'},
  {id:213, reading:'キロ/キロメートル', kanjis:'', type:'n,pref', meaning:'kilo (kilometre)'},
  {id:214, reading:'ぎんこう', kanjis:'銀行', type:'n', meaning:'bank'},
  {id:215, reading:'きんようび', kanjis:'金曜日', type:'n-adv,n', meaning:'Friday'}, 
  {id:216, reading:'く', kanjis:'九', type:'number', meaning:'nine'},
  {id:217, reading:'くすり', kanjis:'薬', type:'n', meaning:'medicine'},
  {id:218, reading:'ください', kanjis:'', type:'kana only', meaning:'(with te-form verb) please do for me'},
  {id:219, reading:'くだもの', kanjis:'果物', type:'n', meaning:'fruit'},
  {id:220, reading:'くち', kanjis:'口', type:'n', meaning:'mouth, orifice, opening'},
  {id:221, reading:'くつ', kanjis:'靴', type:'n', meaning:'shoes, footwear'},
  {id:222, reading:'くつした', kanjis:'靴下', type:'n', meaning:'socks'},
  {id:223, reading:'くに', kanjis:'国', type:'n', meaning:'country'},
  {id:224, reading:'くもり', kanjis:'曇り', type:'adv', meaning:'cloudiness, cloudy weather'},
  {id:225, reading:'くもる', kanjis:'曇る', type:'u-v', meaning:'to become cloudy, to become dim'},
  {id:226, reading:'くらい', kanjis:'暗い', type:'adj', meaning:'dark, gloomy'},
  {id:227, reading:'～くらい/ぐらい', kanjis:'', type:'suf', meaning:'approximate (quantity)'},
  {id:228, reading:'クラス', kanjis:'', type:'n', meaning:'class'},
  {id:229, reading:'グラム', kanjis:'', type:'n', meaning:'gram'},
  {id:230, reading:'くる', kanjis:'来る', type:'vk', meaning:'to come'},
  {id:231, reading:'くるま', kanjis:'車', type:'n', meaning:'car, vehicle'},
  {id:232, reading:'くろ', kanjis:'黒', type:'n', meaning:'black'},
  {id:233, reading:'くろい', kanjis:'黒い', type:'adj', meaning:'black'},
  {id:234, reading:'けいかん', kanjis:'警官', type:'n', meaning:'policeman'},
  {id:235, reading:'けさ', kanjis:'今朝', type:'n-temp', meaning:'this morning'},
  {id:236, reading:'けす', kanjis:'消す', type:'u-v', meaning:'to erase, to delete, to turn off power'},
  {id:237, reading:'けっこう', kanjis:'結構', type:'na-adj,n-adv,n', meaning:'nice, enough'},
  {id:238, reading:'けっこん（する）', kanjis:'結婚', type:'adj-no,n,vs', meaning:'marriage'},
  {id:239, reading:'げつようび', kanjis:'月曜日', type:'n-adv,n', meaning:'Monday'},
  {id:240, reading:'げんかん', kanjis:'玄関', type:'n', meaning:'entrance-way, entry hall'},
  {id:241, reading:'げんき', kanjis:'元気', type:'na-adj,n', meaning:'health'},
  {id:242, reading:'～こ', kanjis:'～個', type:'n,suf', meaning:'counter for small items'},
  {id:243, reading:'ご', kanjis:'五', type:'num', meaning:'five'},
  {id:244, reading:'～ご', kanjis:'～語', type:'n,n-suf', meaning:'word, language'},
  {id:245, reading:'こうえん', kanjis:'公園', type:'n', meaning:'(public) park'},
  {id:246, reading:'こうさてん', kanjis:'交差点', type:'n', meaning:'intersection'},
  {id:247, reading:'こうちゃ', kanjis:'紅茶', type:'n', meaning:'black tea'},
  {id:248, reading:'こうばん', kanjis:'交番', type:'n', meaning:'police box'},
  {id:249, reading:'こえ', kanjis:'声', type:'n', meaning:'voice'},
  {id:250, reading:'コート', kanjis:'', type:'n', meaning:'coat'},
  {id:251, reading:'コーヒー', kanjis:'', type:'n', meaning:'coffee'},
  {id:252, reading:'ここ', kanjis:'', type:'n', meaning:'here, this place'},
  {id:253, reading:'ごご', kanjis:'午後', type:'n-adv,n-t', meaning:'afternoon, P.M.'},
  {id:254, reading:'ここのか', kanjis:'九日', type:'', meaning:'nine days, the ninth day (of the month)'},
  {id:255, reading:'ここのつ', kanjis:'九つ', type:'n', meaning:'nine'},
  {id:256, reading:'ごぜん', kanjis:'午前', type:'n-adv,n-t', meaning:'morning, A.M.'},
  {id:257, reading:'こたえる', kanjis:'答える', type:'ru-v', meaning:'to answer, to reply'},
  {id:258, reading:'こちら', kanjis:'', type:'n', meaning:'this eg person, way'},
  {id:259, reading:'こっち', kanjis:'', type:'n', meaning:'this eg person, way'},
  {id:260, reading:'コップ', kanjis:'', type:'n', meaning:'cup'},
  {id:261, reading:'ことし', kanjis:'今年', type:'n-adv,n-t', meaning:'this year'},
  {id:262, reading:'ことば', kanjis:'言葉', type:'n', meaning:'word'},
  {id:263, reading:'こども', kanjis:'子供', type:'n', meaning:'child, children'},
  {id:264, reading:'この', kanjis:'', type:'adj-pn,int', meaning:'this'},
  {id:265, reading:'ごはん', kanjis:'御飯', type:'n', meaning:'rice (cooked), meal'},
  {id:266, reading:'コピー・する', kanjis:'', type:'n,p-suru', meaning:'to copy'},
  {id:267, reading:'こまる', kanjis:'困る', type:'u-v', meaning:'to be worried, to be bothered'},
  {id:268, reading:'これ', kanjis:'', type:'int,n', meaning:'this'},
  {id:269, reading:'～ころ/～ごろ', kanjis:'', type:'n-suf', meaning:'about, approximately (time)'},
  {id:270, reading:'こんげつ', kanjis:'今月', type:'n-adv,n-t', meaning:'this month'},
  {id:271, reading:'こんしゅう', kanjis:'今週', type:'n-adv,n-t', meaning:'this week'},
  {id:272, reading:'こんな', kanjis:'', type:'na-adj,adj-pn,adv,n', meaning:'such, like this'},
  {id:273, reading:'こんばん', kanjis:'今晩', type:'n-adv,n-t', meaning:'tonight, this evening'},
  {id:274, reading:'さあ', kanjis:'', type:'conj,int', meaning:'come now, well'},
  {id:275, reading:'～さい', kanjis:'～歳', type:'suf', meaning:'～years-old'},
  {id:276, reading:'さいふ', kanjis:'財布', type:'n', meaning:'wallet'},
  {id:277, reading:'さかな', kanjis:'魚', type:'n', meaning:'fish'},
  {id:278, reading:'さき', kanjis:'先', type:'adj-no,n,n-suf,pref', meaning:'the future, former, previous'},
  {id:279, reading:'さく', kanjis:'咲く', type:'u-v', meaning:'to bloom'}, 
  {id:280, reading:'さくぶん', kanjis:'作文', type:'n', meaning:'composition, writing'},
  {id:281, reading:'さす', kanjis:'差す', type:'u-v', meaning:'to raise (stretch out) hands, to raise (eg umbrella)'},
  {id:282, reading:'～さつ', kanjis:'～冊', type:'n', meaning:'counter for books'},
  {id:283, reading:'ざっし', kanjis:'雑誌', type:'n', meaning:'magazine'},
  {id:284, reading:'さとう', kanjis:'砂糖', type:'n', meaning:'sugar'},
  {id:285, reading:'さむい', kanjis:'寒い', type:'adj', meaning:'cold (e.g. weather)'},
  {id:286, reading:'さらいねん', kanjis:'さ来年', type:'n-adv,n-t', meaning:'year after next'},
  {id:287, reading:'～さん', kanjis:'', type:'suf', meaning:'Mr or Mrs'},
  {id:288, reading:'さん', kanjis:'三', type:'num', meaning:'three'},
  {id:289, reading:'さんぽ（する）', kanjis:'散歩', type:'n,vs', meaning:'walk, stroll'},
  {id:290, reading:'し', kanjis:'四', type:'num', meaning:'four'},
  {id:291, reading:'～じ', kanjis:'～時', type:'suf', meaning:'time (～ O\'clock)'},
  {id:292, reading:'しお', kanjis:'塩', type:'n', meaning:'salt'},
  {id:293, reading:'しかし', kanjis:'', type:'conj', meaning:'however, but'},
  {id:294, reading:'じかん', kanjis:'時間', type:'n-adv,n', meaning:'time'},
  {id:295, reading:'～じかん', kanjis:'～時間', type:'suf', meaning:'～hours'},
  {id:296, reading:'しごと', kanjis:'仕事', type:'adj-no,n', meaning:'work, occupation, employment'},
  {id:297, reading:'じしょ', kanjis:'辞書', type:'n', meaning:'dictionary'},
  {id:298, reading:'しずか', kanjis:'静か', type:'na-adj', meaning:'quiet, peaceful'},
  {id:299, reading:'した', kanjis:'下', type:'n', meaning:'under, below, beneath'},
  {id:300, reading:'しち', kanjis:'七', type:'num', meaning:'seven'},
  {id:301, reading:'しつもん', kanjis:'質問', type:'n,vs', meaning:'question, inquiry'},
  {id:302, reading:'じてんしゃ', kanjis:'自転車', type:'n', meaning:'bicycle'},
  {id:303, reading:'じどうしゃ', kanjis:'自動車', type:'n', meaning:'automobile'},
  {id:304, reading:'しぬ', kanjis:'死ぬ', type:'v5n', meaning:'to die'},
  {id:305, reading:'じびき', kanjis:'字引', type:'n', meaning:'dictionary'},
  {id:306, reading:'じぶん', kanjis:'自分', type:'n', meaning:'myself, oneself'},
  {id:307, reading:'しまる', kanjis:'閉まる', type:'u-v,vi', meaning:'to close, to be closed'},
  {id:308, reading:'しめる', kanjis:'閉める', type:'ru-v,vt', meaning:'to close, to shut'},
  {id:309, reading:'しめる', kanjis:'締める', type:'ru-v', meaning:'to tie, to fasten'},
  {id:310, reading:'じゃ/じゃあ', kanjis:'', type:'conj,int', meaning:'well, well then'},
  {id:311, reading:'しゃしん', kanjis:'写真', type:'n', meaning:'photograph'}, 
  {id:312, reading:'シャツ', kanjis:'', type:'n', meaning:'shirt, singlet'},
  {id:313, reading:'シャワー', kanjis:'', type:'n', meaning:'shower'},
  {id:314, reading:'じゅう', kanjis:'十', type:'num', meaning:'ten'},
  {id:315, reading:'～じゅう', kanjis:'～中', type:'suf', meaning:'during, while'},
  {id:316, reading:'～しゅうかん', kanjis:'～週間', type:'suf', meaning:'～weeks'},
  {id:317, reading:'じゅぎょう', kanjis:'授業', type:'n,vs', meaning:'lesson, class work'},
  {id:318, reading:'しゅくだい', kanjis:'宿題', type:'n', meaning:'homework'},
  {id:319, reading:'じょうず', kanjis:'上手', type:'na-adj,n', meaning:'skill, skillful, dexterity'},
  {id:320, reading:'じょうぶ', kanjis:'丈夫', type:'na-adj,n', meaning:'strong, solid, durable'},
  {id:321, reading:'しょうゆ', kanjis:'', type:'n', meaning:'soy sauce'},
  {id:322, reading:'しょくどう', kanjis:'食堂', type:'n', meaning:'cafeteria, dining hall'},
  {id:323, reading:'しる', kanjis:'知る', type:'u-v', meaning:'to know, to understand'},
  {id:324, reading:'しろ', kanjis:'白', type:'n', meaning:'white'},
  {id:325, reading:'しろい', kanjis:'白い', type:'adj', meaning:'white'},
  {id:326, reading:'～にん', kanjis:'～人', type:'n,suf', meaning:'counter for people'},
  {id:327, reading:'しんぶん', kanjis:'新聞', type:'n', meaning:'newspaper'},
  {id:328, reading:'すいようび', kanjis:'水曜日', type:'n-adv,n', meaning:'Wednesday'},
  {id:329, reading:'すう', kanjis:'吸う', type:'u-v', meaning:'to smoke, to breathe in, to suck'},
  {id:330, reading:'スカート', kanjis:'', type:'n', meaning:'skirt'},
  {id:331, reading:'すき', kanjis:'好き', type:'na-adj,n', meaning:'liking, fondness, love'},
  {id:332, reading:'～すぎ', kanjis:'', type:'suf', meaning:'to exceed, ～ too much'},
  {id:333, reading:'すくない', kanjis:'少ない', type:'adj', meaning:'a few, scarce'},
  {id:334, reading:'すぐ・に', kanjis:'', type:'adv', meaning:'immediately, instantly'},
  {id:335, reading:'すこし', kanjis:'少し', type:'adv,n', meaning:'little, few'},
  {id:336, reading:'すずしい', kanjis:'涼しい', type:'adj', meaning:'cool, refreshing'},
  {id:337, reading:'～ずつ', kanjis:'', type:'suf', meaning:'at a time, gradually'},
  {id:338, reading:'ストーブ', kanjis:'', type:'n', meaning:'heater (lit: stove)'},
  {id:339, reading:'スプーン', kanjis:'', type:'n', meaning:'spoon'},
  {id:340, reading:'スポーツ', kanjis:'', type:'n', meaning:'sport'},
  {id:341, reading:'ズボン', kanjis:'', type:'n', meaning:'trousers (fr: jupon)'},
  {id:342, reading:'すむ', kanjis:'住む', type:'u-v', meaning:'to reside, to live in'},
  {id:343, reading:'スリッパ', kanjis:'', type:'n', meaning:'slippers'},
  {id:344, reading:'する', kanjis:'', type:'vs-i', meaning:'to do, to try'},
  {id:345, reading:'すわる', kanjis:'座る', type:'u-v', meaning:'to sit'},
  {id:346, reading:'せい', kanjis:'背', type:'n', meaning:'height, stature'},
  {id:347, reading:'せいと', kanjis:'生徒', type:'n', meaning:'pupil'},
  {id:348, reading:'セーター', kanjis:'', type:'n', meaning:'sweater, jumper'},
  {id:349, reading:'せっけん', kanjis:'石鹸', type:'n', meaning:'soap'},
  {id:350, reading:'せびろ', kanjis:'背広', type:'n', meaning:'business suit'},
  {id:351, reading:'せまい', kanjis:'狭い', type:'adj', meaning:'narrow, confined, small'},
  {id:352, reading:'ゼロ', kanjis:'', type:'n', meaning:'zero'},
  {id:353, reading:'せん', kanjis:'千', type:'', meaning:'thousand, many'},
  {id:354, reading:'せんげつ', kanjis:'先月', type:'n-adv,n-t', meaning:'last month'},
  {id:355, reading:'せんしゅう', kanjis:'先週', type:'n-adv,n-t', meaning:'last week, the week before'},
  {id:356, reading:'せんせい', kanjis:'先生', type:'n', meaning:'teacher, master, doctor'},
  {id:357, reading:'せんたく', kanjis:'洗濯', type:'n,vs', meaning:'washing, laundry'},
  {id:358, reading:'ぜんぶ', kanjis:'全部', type:'n-adv,n-t', meaning:'all, entire, whole'},
  {id:359, reading:'そう/そうです', kanjis:'', type:'', meaning:'appears, to be the case'},
  {id:360, reading:'そうじ（する）', kanjis:'掃除', type:'n,vs', meaning:'cleaning, sweeping'},
  {id:361, reading:'そうして/そして', kanjis:'', type:'conj', meaning:'and, like that'},
  {id:362, reading:'そこ', kanjis:'', type:'n', meaning:'that place, there'},
  {id:363, reading:'そちら', kanjis:'', type:'n', meaning:'over there'},
  {id:364, reading:'そっち', kanjis:'', type:'n', meaning:'over there'},
  {id:365, reading:'そと', kanjis:'外', type:'n', meaning:'outside, exterior'},
  {id:366, reading:'その', kanjis:'', type:'adj-pn', meaning:'that'},
  {id:367, reading:'そば', kanjis:'', type:'n', meaning:'near, close, beside'},
  {id:368, reading:'そら', kanjis:'空', type:'n', meaning:'sky'},
  {id:369, reading:'それ', kanjis:'', type:'n', meaning:'it, that'},
  {id:370, reading:'それから', kanjis:'', type:'uk', meaning:'and then, after that'},
  {id:371, reading:'それでは', kanjis:'', type:'exp', meaning:'in that situation, well then...'},
  {id:372, reading:'～だい', kanjis:'～台', type:'suf', meaning:'counter for vehicles/machines'},
  {id:373, reading:'だいがく', kanjis:'大学', type:'n', meaning:'university'},
  {id:374, reading:'たいしかん', kanjis:'大使館', type:'n', meaning:'embassy'},
  {id:375, reading:'だいじょうぶ', kanjis:'大丈夫', type:'na-adj,adv,n', meaning:'safe, all right, O.K.'},
  {id:376, reading:'だいすき', kanjis:'大好き', type:'na-adj,n', meaning:'very likeable, like very much'},
  {id:377, reading:'たいせつ', kanjis:'大切', type:'na-adj,n', meaning:'important'},
  {id:378, reading:'だいどころ', kanjis:'台所', type:'n', meaning:'kitchen'},
  {id:379, reading:'たいへん', kanjis:'', type:'na-adj,adv,n', meaning:'very'},
  {id:380, reading:'たいへん', kanjis:'', type:'na-adj,adv,n', meaning:'difficult situation, tough situation'},
  {id:381, reading:'たかい', kanjis:'高い', type:'adj', meaning:'tall, high'},
  {id:382, reading:'たかい', kanjis:'高い', type:'adj', meaning:'expensive'},
  {id:383, reading:'～だけ', kanjis:'', type:'prt', meaning:'only ～, just ～'}, 
  {id:384, reading:'たくさん', kanjis:'', type:'na-adj,adv,n', meaning:'many, a lot, much'},
  {id:385, reading:'タクシー', kanjis:'', type:'n', meaning:'taxi'},
  {id:386, reading:'だす', kanjis:'出す', type:'u-v', meaning:'to put out, to send'},
  {id:387, reading:'～たち', kanjis:'', type:'n-suf', meaning:'plural suffix'},
  {id:388, reading:'たつ', kanjis:'立つ', type:'u-v', meaning:'to stand'},
  {id:389, reading:'たて', kanjis:'', type:'n', meaning:'length, height'},
  {id:390, reading:'たてもの', kanjis:'建物', type:'n', meaning:'building'},
  {id:391, reading:'たのしい', kanjis:'楽しい', type:'adj', meaning:'enjoyable, fun'},
  {id:392, reading:'たのむ', kanjis:'頼む', type:'u-v', meaning:'to request, to ask'},
  {id:393, reading:'たばこ', kanjis:'', type:'n', meaning:'tobacco, cigarettes'},
  {id:394, reading:'たぶん', kanjis:'', type:'adv,n', meaning:'perhaps, probably'},
  {id:395, reading:'たべもの', kanjis:'食べ物', type:'n', meaning:'food'},
  {id:396, reading:'たべる', kanjis:'食べる', type:'ru-v', meaning:'to eat'},
  {id:397, reading:'たまご', kanjis:'卵', type:'n', meaning:'egg(s)'},
  {id:398, reading:'だれ', kanjis:'誰', type:'n', meaning:'who'},
  {id:399, reading:'だれか', kanjis:'誰か', type:'n', meaning:'someone, somebody'},
  {id:400, reading:'たんじょうび', kanjis:'誕生日', type:'n', meaning:'birthday'},
  {id:401, reading:'だんだん', kanjis:'', type:'adv,n', meaning:'gradually, by degrees'},
  {id:402, reading:'ちいさい', kanjis:'小さい', type:'adj', meaning:'small, little'},
  {id:403, reading:'ちいさな', kanjis:'小さな', type:'na-adj', meaning:'small, little'},
  {id:404, reading:'ちかい', kanjis:'近い', type:'adj,suf', meaning:'near, close by, short'},
  {id:405, reading:'ちがう', kanjis:'違う', type:'u-v', meaning:'to differ (from)'},
  {id:406, reading:'ちかく', kanjis:'近く', type:'n-adv,n', meaning:'near'},
  {id:407, reading:'ちかてつ', kanjis:'地下鉄', type:'n', meaning:'underground train, subway'},
  {id:408, reading:'ちず', kanjis:'地図', type:'n', meaning:'map'},
  {id:409, reading:'ちち', kanjis:'父', type:'n', meaning:'(one\'s own) father'},
  {id:410, reading:'ちゃいろ', kanjis:'茶色', type:'n', meaning:'brown'},
  {id:411, reading:'ちゃわん', kanjis:'', type:'n', meaning:'rice bowl'},
  {id:412, reading:'～ちゅう', kanjis:'～中', type:'suf', meaning:'during, while ～ing'},
  {id:413, reading:'ちょうど', kanjis:'', type:'gn', meaning:'just, right, exactly'}, 
  {id:414, reading:'ちょっと', kanjis:'', type:'adv,int', meaning:'a little, somewhat'},
  {id:415, reading:'ついたち', kanjis:'一日', type:'n', meaning:'for one day, first of month'},
  {id:416, reading:'つかう', kanjis:'使う', type:'u-v', meaning:'to use'},
  {id:417, reading:'つかれる', kanjis:'疲れる', type:'ru-v', meaning:'to get tired, to tire'},
  {id:418, reading:'つぎ', kanjis:'次', type:'n', meaning:'next'},
  {id:419, reading:'つく', kanjis:'着く', type:'u-v', meaning:'to arrive at, to reach'},
  {id:420, reading:'つくえ', kanjis:'机', type:'n', meaning:'desk'},
  {id:421, reading:'つくる', kanjis:'作る', type:'u-v', meaning:'to make, to create'},
  {id:422, reading:'つける', kanjis:'', type:'ru-v,vt', meaning:'to turn on (eg a light)'},
  {id:423, reading:'つとめる', kanjis:'勤める', type:'ru-v', meaning:'to serve, to work (for)'},
  {id:424, reading:'つまらない', kanjis:'', type:'adj', meaning:'insignificant, boring'},
  {id:425, reading:'つめたい', kanjis:'冷たい', type:'adj', meaning:'cold (to the touch)'},
  {id:426, reading:'つよい', kanjis:'強い', type:'adj', meaning:'strong, powerful'},
  {id:427, reading:'て', kanjis:'手', type:'n', meaning:'hand'},
  {id:428, reading:'テープ', kanjis:'', type:'n', meaning:'tape'},
  {id:429, reading:'テープレコーダー', kanjis:'', type:'n', meaning:'tape recorder'},
  {id:430, reading:'テーブル', kanjis:'', type:'n', meaning:'table'},
  {id:431, reading:'でかける', kanjis:'出かける', type:'ru-v', meaning:'to depart, to go out'},
  {id:432, reading:'てがみ', kanjis:'手紙', type:'n', meaning:'letter'},
  {id:433, reading:'できる', kanjis:'', type:'ru-v', meaning:'to be able to'},
  {id:434, reading:'でぐち', kanjis:'出口', type:'n', meaning:'exit'},
  {id:435, reading:'テスト', kanjis:'', type:'n,vs', meaning:'test'},
  {id:436, reading:'では', kanjis:'', type:'expr', meaning:'with that...'},
  {id:437, reading:'デパート', kanjis:'', type:'n', meaning:'department store'},
  {id:438, reading:'でも', kanjis:'', type:'conj,prt', meaning:'but, however'},
  {id:439, reading:'でる', kanjis:'出る', type:'ru-v', meaning:'to appear, to leave'},
  {id:440, reading:'テレビ', kanjis:'', type:'n', meaning:'television, TV'},
  {id:441, reading:'てんき', kanjis:'天気', type:'n', meaning:'weather'},
  {id:442, reading:'でんき', kanjis:'電気', type:'n', meaning:'electricity, (electric) light'},
  {id:443, reading:'でんしゃ', kanjis:'電車', type:'n', meaning:'electric train'},
  {id:444, reading:'でんわ', kanjis:'電話', type:'n,vs', meaning:'telephone'},
  {id:445, reading:'と', kanjis:'戸', type:'n', meaning:'door (Japanese style)'},
  {id:446, reading:'～ど', kanjis:'～度', type:'n-suf', meaning:'counter for occurrences'},
  {id:447, reading:'ドア', kanjis:'', type:'n', meaning:'door (Western style)'},
  {id:448, reading:'トイレ', kanjis:'', type:'n', meaning:'toilet'},
  {id:449, reading:'どう', kanjis:'', type:'adv', meaning:'how, in what way'},
  {id:450, reading:'どうして', kanjis:'', type:'adv,int', meaning:'why?, for what reason'},
  {id:451, reading:'どうぞ', kanjis:'', type:'adv', meaning:'please, kindly, by all means'},
  {id:452, reading:'どうぶつ', kanjis:'動物', type:'n', meaning:'animal'},
  {id:453, reading:'どうも', kanjis:'', type:'adv,int', meaning:'thanks, very'},
  {id:454, reading:'とお', kanjis:'十', type:'num', meaning:'ten'},
  {id:455, reading:'とおい', kanjis:'遠い', type:'adj', meaning:'far, distant'},
  {id:456, reading:'とおか', kanjis:'十日', type:'', meaning:'ten days, the tenth (day of the month)'},
  {id:457, reading:'～とき', kanjis:'～時', type:'adv,n', meaning:'at the time of ～'},
  {id:458, reading:'ときどき', kanjis:'時々', type:'adv,n', meaning:'sometimes'},
  {id:459, reading:'とけい', kanjis:'時計', type:'n', meaning:'watch, clock'},
  {id:460, reading:'どこ', kanjis:'', type:'n', meaning:'where, what place'},
  {id:461, reading:'ところ', kanjis:'所', type:'n', meaning:'place'}, 
  {id:462, reading:'とし', kanjis:'年', type:'n', meaning:'year, age'},
  {id:463, reading:'としょかん', kanjis:'図書館', type:'n', meaning:'library'},
  {id:464, reading:'どちら', kanjis:'', type:'n', meaning:'which, which way'},
  {id:465, reading:'どっち', kanjis:'', type:'n', meaning:'which one, which way'},
  {id:466, reading:'とても', kanjis:'', type:'adv', meaning:'very'},
  {id:467, reading:'どなた', kanjis:'', type:'n', meaning:'who'},
  {id:468, reading:'となり', kanjis:'隣', type:'n', meaning:'next to, next door to'},
  {id:469, reading:'どの', kanjis:'', type:'pren-adj', meaning:'which'},
  {id:470, reading:'とぶ', kanjis:'飛ぶ', type:'u-v', meaning:'to fly, to hop'},
  {id:471, reading:'とまる', kanjis:'止まる', type:'u-v', meaning:'to come to a halt'},
  {id:472, reading:'ともだち', kanjis:'友達', type:'n', meaning:'friend'},
  {id:473, reading:'どようび', kanjis:'土曜日', type:'n-adv,n', meaning:'Saturday'},
  {id:474, reading:'とり', kanjis:'鳥', type:'n', meaning:'bird'},
  {id:475, reading:'とりにく', kanjis:'とり肉', type:'n', meaning:'chicken meat'},
  {id:476, reading:'とる', kanjis:'取る', type:'u-v', meaning:'to take'},
  {id:477, reading:'とる', kanjis:'撮る', type:'u-v', meaning:'to take (a photo)'},
  {id:478, reading:'どれ', kanjis:'', type:'n', meaning:'which (of three or more)'},
  {id:479, reading:'どんな', kanjis:'', type:'na-adj,adj-pn,n', meaning:'what, what kind of'},
  {id:480, reading:'ない', kanjis:'', type:'adj', meaning:'there isn\'t, doesn\'t have'},
  {id:481, reading:'ナイフ', kanjis:'', type:'n', meaning:'knife'},
  {id:482, reading:'なか', kanjis:'中', type:'n', meaning:'inside, middle, among'},
  {id:483, reading:'ながい', kanjis:'長い', type:'adj', meaning:'long'},
  {id:484, reading:'～ながら', kanjis:'', type:'prt', meaning:'while ~ing, during, although'},
  {id:485, reading:'なく', kanjis:'鳴く', type:'u-v', meaning:'to sing (bird), to make sound (animal)'},
  {id:486, reading:'なくす', kanjis:'無くす', type:'u-v', meaning:'to lose something'},
  {id:487, reading:'なぜ', kanjis:'', type:'adv', meaning:'why'},
  {id:488, reading:'なつ', kanjis:'夏', type:'n-adv,n-t', meaning:'summer'},
  {id:489, reading:'なつやすみ', kanjis:'夏休み', type:'n', meaning:'summer vacation, summer holiday'},
  {id:490, reading:'～など', kanjis:'', type:'n,n-suf,prt', meaning:'et cetera'},
  {id:491, reading:'ななつ', kanjis:'七つ', type:'n', meaning:'seven'},
  {id:492, reading:'なん/なに', kanjis:'何', type:'int,n', meaning:'what'},
  {id:493, reading:'なのか', kanjis:'七日', type:'n-adv', meaning:'seven days, the seventh day (of the month)'},
  {id:494, reading:'なまえ', kanjis:'名前', type:'n', meaning:'name'},
  {id:495, reading:'ならう', kanjis:'習う', type:'u-v', meaning:'to learn'},
  {id:496, reading:'ならぶ', kanjis:'並ぶ', type:'u-v,vi', meaning:'to line up, to stand in a line'},
  {id:497, reading:'ならべる', kanjis:'並べる', type:'ru-v,vt', meaning:'to line up, to set up'},
  {id:498, reading:'なる', kanjis:'', type:'u-v', meaning:'to become'},
  {id:499, reading:'なん～', kanjis:'何～', type:'', meaning:'what sort of ～'},
  {id:500, reading:'に', kanjis:'二', type:'num', meaning:'two'},
  {id:501, reading:'にぎやか', kanjis:'', type:'na-adj,n', meaning:'bustling, busy'},
  {id:502, reading:'にく', kanjis:'肉', type:'n', meaning:'meat'},
  {id:503, reading:'にし', kanjis:'西', type:'n', meaning:'west'},
  {id:504, reading:'～にち', kanjis:'～日', type:'', meaning:'～ day of the month, for ～ days'},
  {id:505, reading:'にちようび', kanjis:'日曜日', type:'n-adv,n', meaning:'Sunday'},
  {id:506, reading:'にもつ', kanjis:'荷物', type:'n', meaning:'luggage'},
  {id:507, reading:'ニュース', kanjis:'', type:'n', meaning:'news'},
  {id:508, reading:'にわ', kanjis:'庭', type:'n', meaning:'garden'},
  {id:509, reading:'～にん', kanjis:'～人', type:'', meaning:'counter for people'},
  {id:510, reading:'ぬぐ', kanjis:'脱ぐ', type:'u-v', meaning:'to take off clothes'},
  {id:511, reading:'ぬるい', kanjis:'温い', type:'adj', meaning:'lukewarm'},
  {id:512, reading:'ネクタイ', kanjis:'', type:'n', meaning:'tie, necktie'},
  {id:513, reading:'ねこ', kanjis:'猫', type:'n', meaning:'cat'},
  {id:514, reading:'ねる', kanjis:'寝る', type:'ru-v', meaning:'to go to bed, to sleep'},
  {id:515, reading:'～ねん', kanjis:'～年', type:'', meaning:'～ years'},
  {id:516, reading:'ノート', kanjis:'', type:'n', meaning:'notebook, exercise book'},
  {id:517, reading:'のぼる', kanjis:'登る', type:'u-v', meaning:'to climb'},
  {id:518, reading:'のみもの', kanjis:'飲み物', type:'n', meaning:'drink, beverage'}, 
  {id:519, reading:'のむ', kanjis:'飲む', type:'u-v', meaning:'to drink'},
  {id:520, reading:'のる', kanjis:'乗る', type:'u-v', meaning:'to get on, to ride in, to board'},
  {id:521, reading:'は', kanjis:'歯', type:'n', meaning:'tooth'},
  {id:522, reading:'パーティー', kanjis:'', type:'n', meaning:'party'},
  {id:523, reading:'はい', kanjis:'', type:'conj,int', meaning:'yes'},
  {id:524, reading:'～はい', kanjis:'～杯', type:'n', meaning:'counter for cupfuls'},
  {id:525, reading:'はいざら', kanjis:'灰皿', type:'n', meaning:'ashtray'},
  {id:526, reading:'はいる', kanjis:'入る', type:'u-v', meaning:'to enter, to contain, to hold'},
  {id:527, reading:'はがき', kanjis:'葉書', type:'n', meaning:'postcard'},
  {id:528, reading:'はく', kanjis:'', type:'u-v', meaning:'to wear, to put on (trousers)'},
  {id:529, reading:'はこ', kanjis:'箱', type:'n', meaning:'box'},
  {id:530, reading:'はし', kanjis:'橋', type:'n', meaning:'bridge'},
  {id:531, reading:'はし', kanjis:'', type:'n', meaning:'chopsticks'},
  {id:532, reading:'はじまる', kanjis:'始まる', type:'u-v,vi', meaning:'to begin'},
  {id:533, reading:'はじめ', kanjis:'初め/始め', type:'expr', meaning:'beginning, start'},
  {id:534, reading:'はじめて', kanjis:'初めて', type:'adv,n', meaning:'for the first time'},
  {id:535, reading:'はしる', kanjis:'走る', type:'u-v', meaning:'to run'},
  {id:536, reading:'バス', kanjis:'', type:'n', meaning:'bus'},
  {id:537, reading:'バター', kanjis:'', type:'n', meaning:'butter'},
  {id:538, reading:'はたち', kanjis:'二十歳', type:'n', meaning:'20 years old, 20th year'},
  {id:539, reading:'はたらく', kanjis:'働く', type:'u-v', meaning:'to work'},
  {id:540, reading:'はち', kanjis:'八', type:'num', meaning:'eight'},
  {id:541, reading:'はつか', kanjis:'二十日', type:'n', meaning:'twenty days, twentieth (day of the month)'},
  {id:542, reading:'はな', kanjis:'花', type:'n', meaning:'flower'},
  {id:543, reading:'はな', kanjis:'鼻', type:'n', meaning:'nose'},
  {id:544, reading:'はなし', kanjis:'話', type:'n', meaning:'talk, story'},
  {id:545, reading:'はなす', kanjis:'話す', type:'u-v', meaning:'to speak'},
  {id:546, reading:'はは', kanjis:'母', type:'n', meaning:'(one\'s own) mother'},
  {id:547, reading:'はやい', kanjis:'早い', type:'adj', meaning:'early'},
  {id:548, reading:'はやい', kanjis:'速い', type:'adj', meaning:'quick, fast'},
  {id:549, reading:'はる', kanjis:'春', type:'n-adv,n-t', meaning:'spring'},
  {id:550, reading:'はる', kanjis:'貼る', type:'u-v', meaning:'to stick, to paste'},
  {id:551, reading:'はれ', kanjis:'晴れ', type:'ru-v', meaning:'clear weather'}, 
  {id:552, reading:'はれる', kanjis:'晴れる', type:'ru-v', meaning:'to be sunny'},
  {id:553, reading:'はん', kanjis:'半', type:'n-adv,n,n-suf', meaning:'half'},
  {id:554, reading:'ばん', kanjis:'晩', type:'n-adv,n-t', meaning:'evening'},
  {id:555, reading:'～ばん', kanjis:'～番', type:'n-adv,n-t', meaning:'～st/th best'},
  {id:556, reading:'パン', kanjis:'', type:'n', meaning:'bread'},
  {id:557, reading:'ハンカチ', kanjis:'', type:'n', meaning:'handkerchief'},
  {id:558, reading:'ばんごう', kanjis:'番号', type:'n', meaning:'number'},
  {id:559, reading:'ばんごはん', kanjis:'晩御飯', type:'n', meaning:'dinner, evening meal'},
  {id:560, reading:'はんぶん', kanjis:'半分', type:'', meaning:'half'},
  {id:561, reading:'ひがし', kanjis:'東', type:'n', meaning:'east'},
  {id:562, reading:'～ひき', kanjis:'～匹', type:'', meaning:'counter for small animals'},
  {id:563, reading:'ひく', kanjis:'引く', type:'u-v', meaning:'to pull'},
  {id:564, reading:'ひく', kanjis:'弾く', type:'u-v', meaning:'to play (piano, guitar)'},
  {id:565, reading:'ひくい', kanjis:'低い', type:'adj', meaning:'short, low'},
  {id:566, reading:'ひこうき', kanjis:'飛行機', type:'n', meaning:'aeroplane, airplane'},
  {id:567, reading:'ひだり', kanjis:'左', type:'n', meaning:'left hand side'},
  {id:568, reading:'ひと', kanjis:'人', type:'n', meaning:'man, person'},
  {id:569, reading:'ひとつ', kanjis:'一つ', type:'n', meaning:'one'},
  {id:570, reading:'ひとつき', kanjis:'一月', type:'', meaning:'one month'},
  {id:571, reading:'ひとり', kanjis:'一人', type:'n', meaning:'one person'},
  {id:572, reading:'ひま', kanjis:'暇', type:'na-adj,n', meaning:'free time, leisure'},
  {id:573, reading:'ひゃく', kanjis:'百', type:'num', meaning:'100, hundred'},
  {id:574, reading:'びょういん', kanjis:'病院', type:'n', meaning:'hospital'},
  {id:575, reading:'びょうき', kanjis:'病気', type:'n', meaning:'illness, disease, sickness'},
  {id:576, reading:'ひらがな', kanjis:'平仮名', type:'n', meaning:'hiragana'},
  {id:577, reading:'ひる', kanjis:'昼', type:'n-adv,n-t', meaning:'noon, daytime'},
  {id:578, reading:'ひるごはん', kanjis:'昼御飯', type:'n', meaning:'lunch, midday meal'},
  {id:579, reading:'ひろい', kanjis:'広い', type:'adj', meaning:'spacious, wide'},
  {id:580, reading:'フィルム', kanjis:'', type:'n', meaning:'film (roll of)'},
  {id:581, reading:'ふうとう', kanjis:'封筒', type:'n', meaning:'envelope'},
  {id:582, reading:'プール', kanjis:'', type:'n', meaning:'swimming pool'},
  {id:583, reading:'フォーク', kanjis:'', type:'n', meaning:'fork'},
  {id:584, reading:'ふく', kanjis:'吹く', type:'u-v', meaning:'to blow (wind, etc)'},
  {id:585, reading:'ふく', kanjis:'服', type:'n,n-suf', meaning:'clothes'},
  {id:586, reading:'ふたつ', kanjis:'二つ', type:'n', meaning:'two'},
  {id:587, reading:'ぶたにく', kanjis:'豚肉', type:'n', meaning:'pork'},
  {id:588, reading:'ふたり', kanjis:'二人', type:'n', meaning:'two people'},
  {id:589, reading:'ふつか', kanjis:'二日', type:'n', meaning:'second day of the month, two days'},
  {id:590, reading:'ふとい', kanjis:'太い', type:'adj', meaning:'fat, thick'},
  {id:591, reading:'ふゆ', kanjis:'冬', type:'n-adv,n-t', meaning:'winter'},
  {id:592, reading:'ふる', kanjis:'降る', type:'u-v', meaning:'to precipitate, to fall (e.g. rain)'},
  {id:593, reading:'ふるい', kanjis:'古い', type:'adj', meaning:'old (not person), aged, ancient'},
  {id:594, reading:'ふろ', kanjis:'', type:'n', meaning:'bath'},
  {id:595, reading:'～ふん', kanjis:'～分', type:'suf', meaning:'～minutes'},
  {id:596, reading:'ぶんしょう', kanjis:'文章', type:'suf', meaning:'sentence, text'},
  {id:597, reading:'ページ', kanjis:'', type:'n', meaning:'page'},
  {id:598, reading:'へた', kanjis:'下手', type:'na-adj,n', meaning:'unskillful, poor'},
  {id:599, reading:'ベッド', kanjis:'', type:'n', meaning:'bed'},
  {id:600, reading:'ペット', kanjis:'', type:'n', meaning:'pet'},
  {id:601, reading:'へや', kanjis:'部屋', type:'n', meaning:'room'},
  {id:602, reading:'へん', kanjis:'辺', type:'n', meaning:'area, vicinity'},
  {id:603, reading:'ペン', kanjis:'', type:'n', meaning:'pen'},
  {id:604, reading:'べんきょう（する）', kanjis:'勉強', type:'n,vs', meaning:'study, diligence'},
  {id:605, reading:'べんり', kanjis:'便利', type:'na-adj,n', meaning:'convenient, handy'},
  {id:606, reading:'ほう', kanjis:'', type:'', meaning:'way'},
  {id:607, reading:'ぼうし', kanjis:'帽子', type:'n', meaning:'hat'},
  {id:608, reading:'ボールペン', kanjis:'', type:'n', meaning:'ball-point pen'},
  {id:609, reading:'ほか', kanjis:'外', type:'n', meaning:'other place, the rest'},
  {id:610, reading:'ポケット', kanjis:'', type:'n', meaning:'pocket'},
  {id:611, reading:'ほしい', kanjis:'欲しい', type:'adj', meaning:'want, in need of, desire'},
  {id:612, reading:'ポスト', kanjis:'', type:'n', meaning:'post'},
  {id:613, reading:'ほそい', kanjis:'細い', type:'adj', meaning:'thin, slender, fine'},
  {id:614, reading:'ボタン', kanjis:'', type:'n', meaning:'button'},
  {id:615, reading:'ホテル', kanjis:'', type:'n', meaning:'hotel'},
  {id:616, reading:'ほん', kanjis:'本', type:'n', meaning:'book'},
  {id:617, reading:'～ほん', kanjis:'～本', type:'', meaning:'counter for long cylindrical things'}, 
  {id:618, reading:'ほんだな', kanjis:'本棚', type:'n', meaning:'bookshelves'},
  {id:619, reading:'ほんとう', kanjis:'', type:'adv', meaning:'reality, truth'},
  {id:620, reading:'～まい', kanjis:'～枚', type:'', meaning:'counter for flat things'},
  {id:621, reading:'まいあさ', kanjis:'毎朝', type:'n-adv,n-t', meaning:'every morning'},
  {id:622, reading:'まいげつ/まいつき', kanjis:'毎月', type:'n-adv,n', meaning:'every month, monthly'},
  {id:623, reading:'まいしゅう', kanjis:'毎週', type:'n-adv,n-t', meaning:'every week'},
  {id:624, reading:'まいにち', kanjis:'毎日', type:'n-adv,n-t', meaning:'every day'},
  {id:625, reading:'まいねん/まいとし', kanjis:'毎年', type:'n-t', meaning:'every year, annually'},
  {id:626, reading:'まいばん', kanjis:'毎晩', type:'n-adv,n-t', meaning:'every night'},
  {id:627, reading:'まえ', kanjis:'前', type:'n-adv,n-t,suf', meaning:'before, in front'},
  {id:628, reading:'～まえ', kanjis:'～前', type:'suf', meaning:'in front of ～'},
  {id:629, reading:'まがる', kanjis:'曲る', type:'u-v', meaning:'to turn, to bend'},
  {id:630, reading:'まずい', kanjis:'', type:'adj', meaning:'unappetising, unpleasant (taste)'},
  {id:631, reading:'また', kanjis:'', type:'adv,conj,n', meaning:'again, and'},
  {id:632, reading:'まだ', kanjis:'', type:'adv', meaning:'yet, still, besides'},
  {id:633, reading:'まち', kanjis:'町', type:'n', meaning:'town, city'},
  {id:634, reading:'まつ', kanjis:'待つ', type:'u-v', meaning:'to wait'},
  {id:635, reading:'まっすぐ', kanjis:'', type:'na-adj,adv,n', meaning:'straight (ahead), direct'},
  {id:636, reading:'マッチ', kanjis:'', type:'n', meaning:'match'},
  {id:637, reading:'まど', kanjis:'窓', type:'n', meaning:'window'},
  {id:638, reading:'まるい', kanjis:'丸い/円い', type:'adj', meaning:'round, circular'},
  {id:639, reading:'まん', kanjis:'万', type:'adv,num', meaning:'ten thousand, everything'},
  {id:640, reading:'まんねんひつ', kanjis:'万年筆', type:'n', meaning:'fountain pen'},
  {id:641, reading:'みがく', kanjis:'磨く', type:'u-v', meaning:'to brush (teeth)'},
  {id:642, reading:'みぎ', kanjis:'右', type:'n', meaning:'right hand side'},
  {id:643, reading:'みじかい', kanjis:'短い', type:'adj', meaning:'short'},
  {id:644, reading:'みず', kanjis:'水', type:'n', meaning:'water'},
  {id:645, reading:'みせ', kanjis:'店', type:'n,n-suf', meaning:'store, shop, establishment'},
  {id:646, reading:'みせる', kanjis:'見せる', type:'ru-v', meaning:'to show, to display'},
  {id:647, reading:'みち', kanjis:'道', type:'n', meaning:'road, street'},
  {id:648, reading:'みっか', kanjis:'三日', type:'n', meaning:'three days, the third day (of the month)'},
  {id:649, reading:'みっつ', kanjis:'三つ', type:'n', meaning:'three'},
  {id:650, reading:'みどり', kanjis:'緑', type:'n', meaning:'green'},
  {id:651, reading:'みなさん', kanjis:'皆さん', type:'n', meaning:'everyone'},
  {id:652, reading:'みなみ', kanjis:'南', type:'n,vs', meaning:'South, proceeding south'},
  {id:653, reading:'みみ', kanjis:'耳', type:'n', meaning:'ear'},
  {id:654, reading:'みる', kanjis:'見る', type:'ru-v', meaning:'to see, to watch'},
  {id:655, reading:'みんな', kanjis:'', type:'adv,n', meaning:'all, everyone, everybody'},
  {id:656, reading:'むいか', kanjis:'六日', type:'', meaning:'six days, sixth (day of month)'},
  {id:657, reading:'むこう', kanjis:'向こう', type:'n', meaning:'beyond, over there'},
  {id:658, reading:'むずかしい', kanjis:'難しい', type:'adj', meaning:'difficult'}, 
  {id:659, reading:'むっつ', kanjis:'六つ', type:'num', meaning:'six'},
  {id:660, reading:'むら', kanjis:'村', type:'num', meaning:'village'},
  {id:661, reading:'め', kanjis:'目', type:'n', meaning:'eye, eyeball'},
  {id:662, reading:'メートル', kanjis:'', type:'n', meaning:'metre, meter'},
  {id:663, reading:'めがね', kanjis:'眼鏡', type:'n', meaning:'spectacles, glasses'},
  {id:664, reading:'もう', kanjis:'', type:'adv,int', meaning:'already'},
  {id:665, reading:'もう', kanjis:'', type:'adv,int', meaning:'again'},
  {id:666, reading:'もくようび', kanjis:'木曜日', type:'n-adv,n', meaning:'Thursday'},
  {id:667, reading:'もしもし', kanjis:'', type:'conj,int', meaning:'hello (on phone)'},
  {id:668, reading:'もつ', kanjis:'持つ', type:'u-v', meaning:'(1) to hold, to carry, (2) to possess'},
  {id:669, reading:'もっと', kanjis:'', type:'adv', meaning:'more, longer, farther'},
  {id:670, reading:'もの', kanjis:'物', type:'n', meaning:'thing, object'},
  {id:671, reading:'もん', kanjis:'門', type:'n,n-suf', meaning:'gate'},
  {id:672, reading:'もんだい', kanjis:'問題', type:'n', meaning:'problem, question'},
  {id:673, reading:'～や', kanjis:'屋', type:'n', meaning:'～ shop'},
  {id:674, reading:'やおや', kanjis:'八百屋', type:'n', meaning:'greengrocer'},
  {id:675, reading:'やさい', kanjis:'野菜', type:'n', meaning:'vegetable'},
  {id:676, reading:'やさしい', kanjis:'易しい', type:'adj', meaning:'easy, plain, simple'},
  {id:677, reading:'やすい', kanjis:'安い', type:'adj', meaning:'cheap, inexpensive'},
  {id:678, reading:'やすみ', kanjis:'休み', type:'n', meaning:'rest, vacation, holiday'},
  {id:679, reading:'やすむ', kanjis:'休む', type:'u-v,vi', meaning:'to rest, to have a break, to take a day off'},
  {id:680, reading:'やっつ', kanjis:'八つ', type:'num', meaning:'eight'},
  {id:681, reading:'やま', kanjis:'山', type:'n', meaning:'mountain'},
  {id:682, reading:'やる', kanjis:'', type:'u-v', meaning:'to do'},
  {id:683, reading:'ゆうがた', kanjis:'夕方', type:'n-adv,n-t', meaning:'evening'},
  {id:684, reading:'ゆうはん', kanjis:'夕飯', type:'n', meaning:'dinner'},
  {id:685, reading:'ゆうびんきょく', kanjis:'郵便局', type:'n', meaning:'post office'},
  {id:686, reading:'ゆうべ', kanjis:'昨夜', type:'n', meaning:'last night'},
  {id:687, reading:'ゆうめい', kanjis:'有名', type:'na-adj,n', meaning:'famous'},
  {id:688, reading:'ゆき', kanjis:'雪', type:'n', meaning:'snow'},
  {id:689, reading:'ゆっくり・と', kanjis:'', type:'adv,n', meaning:'slowly, at ease'},
  {id:690, reading:'ようか', kanjis:'八日', type:'n', meaning:'eight days, the eighth (day of the month)'},
  {id:691, reading:'ようふく', kanjis:'洋服', type:'n', meaning:'Western-style clothes'},
  {id:692, reading:'よく', kanjis:'', type:'adv', meaning:'frequently, often'},
  {id:693, reading:'よく', kanjis:'', type:'adv', meaning:'well, skillfully'},
  {id:694, reading:'よこ', kanjis:'横', type:'n', meaning:'beside, side, width'},
  {id:695, reading:'よっか', kanjis:'四日', type:'n', meaning:'(1) 4th day of month, (2) four days'},
  {id:696, reading:'よっつ', kanjis:'四つ', type:'n', meaning:'four'},
  {id:697, reading:'よぶ', kanjis:'呼ぶ', type:'u-v', meaning:'to call out, to invite'},
  {id:698, reading:'よむ', kanjis:'読む', type:'u-v', meaning:'to read'},
  {id:699, reading:'よる', kanjis:'夜', type:'n', meaning:'evening, night'},
  {id:700, reading:'よわい', kanjis:'弱い', type:'adj', meaning:'weak, feable'},
  {id:701, reading:'らいげつ', kanjis:'来月', type:'n-adv,n-t', meaning:'next month'},
  {id:702, reading:'らいしゅう', kanjis:'来週', type:'', meaning:'next week'},
  {id:703, reading:'らいねん', kanjis:'来年', type:'n-adv,n-t', meaning:'next year'},
  {id:704, reading:'ラジオ', kanjis:'', type:'n', meaning:'radio'},
  {id:705, reading:'ラジカセ', kanjis:'', type:'n', meaning:'radio cassette player'},
  {id:706, reading:'りっぱ', kanjis:'', type:'na-adj,n', meaning:'splendid, fine'},
  {id:707, reading:'りゅうがくせい', kanjis:'留学生', type:'n', meaning:'overseas student'},
  {id:708, reading:'りょうしん', kanjis:'両親', type:'n', meaning:'parents, both parents'},
  {id:709, reading:'りょうり', kanjis:'料理', type:'n,vs', meaning:'cooking, cuisine'},
  {id:710, reading:'りょこう', kanjis:'旅行', type:'n,vs', meaning:'travel, trip'},
  {id:711, reading:'れい', kanjis:'零', type:'n', meaning:'zero, nought'},
  {id:712, reading:'れいぞうこ', kanjis:'冷蔵庫', type:'n', meaning:'refrigerator'},
  {id:713, reading:'レコード', kanjis:'', type:'n', meaning:'record'},
  {id:714, reading:'レストラン', kanjis:'', type:'n', meaning:'restaurant'},
  {id:715, reading:'れんしゅう（する）', kanjis:'練習', type:'n,vs', meaning:'(to) practice'},
  {id:716, reading:'ろうか', kanjis:'廊下', type:'n', meaning:'corridor'},
  {id:717, reading:'ろく', kanjis:'六', type:'num', meaning:'six'},
  {id:718, reading:'ワイシャツ', kanjis:'', type:'n', meaning:'shirt (lit: white shirt), business shirt'},
  {id:719, reading:'わかい', kanjis:'若い', type:'adj', meaning:'young'},
  {id:720, reading:'わかる', kanjis:'分かる', type:'u-v', meaning:'to understand'}, 
  {id:721, reading:'わすれる', kanjis:'忘れる', type:'ru-v', meaning:'to forget'},
  {id:722, reading:'わたし', kanjis:'私', type:'adj-no,n', meaning:'I, myself'},
  {id:723, reading:'わたくし', kanjis:'私', type:'adj-no,n', meaning:'I, myself'},
  {id:724, reading:'わたす', kanjis:'渡す', type:'u-v', meaning:'to pass over, to hand over'},
  {id:725, reading:'わたる', kanjis:'渡る', type:'u-v', meaning:'to cross over, to go across'},
  {id:726, reading:'わるい', kanjis:'悪い', type:'adj', meaning:'bad, inferior'}
]